# Generated by Django 2.2 on 2019-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sexe',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
