# Generated by Django 2.2 on 2019-07-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_profile_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
