# Generated by Django 2.2 on 2019-07-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190729_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='langtitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
