# Generated by Django 2.2 on 2019-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190730_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
