# Generated by Django 2.2 on 2019-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190731_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='langtitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
