# Generated by Django 2.2 on 2019-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190804_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='formation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
